function Hd = elliptic
%ELLIPTIC Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
% Generated on: 21-Apr-2021 17:38:40

% Elliptic Highpass filter designed using FDESIGN.HIGHPASS.

% All frequency values are in kHz.
Fs = 50;  % Sampling Frequency

Fstop = 10;      % Stopband Frequency
Fpass = 15;      % Passband Frequency
Astop = 80;      % Stopband Attenuation (dB)
Apass = 1;       % Passband Ripple (dB)
match = 'both';  % Band to match exactly

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.highpass(Fstop, Fpass, Astop, Apass, Fs);
Hd = design(h, 'ellip', 'MatchExactly', match);

% [EOF]
